apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.fullnameOverride }}
  name: {{ .Values.service.fullnameOverride }}
  {{- else }}
  name: {{ include "helm-nginx-chart.fullname" . }}
  {{- end }}
  labels:
    {{- include "helm-nginx-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-nginx-chart.selectorLabels" . | nindent 4 }}
